-- MySQL Script generated by MySQL Workbench
-- 08/19/16 19:08:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `cedula` BIGINT(11) ZEROFILL NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `foto` LONGBLOB NULL,
  `genero` VARCHAR(1) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(1) NOT NULL,
  `tipoSangre` VARCHAR(2) NULL,
  `eps` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`, `cedula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NoNativoDigital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NoNativoDigital` (
  `idnoNativoDigital` INT NULL,
  `apellido` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NULL,
  `documentoIdentificacion` BIGINT(10) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_cedula` BIGINT(11) ZEROFILL NOT NULL,
  PRIMARY KEY (`idnoNativoDigital`, `documentoIdentificacion`, `Usuario_idUsuario`, `Usuario_cedula`),
  INDEX `fk_noNativoDigital_Usuario_idx` (`Usuario_idUsuario` ASC, `Usuario_cedula` ASC),
  CONSTRAINT `fk_noNativoDigital_Usuario`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_cedula`)
    REFERENCES `mydb`.`Usuario` (`idUsuario` , `cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HistoriaClinica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HistoriaClinica` (
  `idhistoriaClinica` INT NOT NULL,
  `fecha` DATE NULL,
  `nivelTriage` INT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_cedula` BIGINT(11) ZEROFILL NOT NULL,
  `Institucion_idInstitucion` INT NOT NULL,
  `Institucion_NIT` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idhistoriaClinica`, `Usuario_idUsuario`, `Usuario_cedula`),
  INDEX `fk_historiaClinica_Usuario1_idx` (`Usuario_idUsuario` ASC, `Usuario_cedula` ASC),
  CONSTRAINT `fk_historiaClinica_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_cedula`)
    REFERENCES `mydb`.`Usuario` (`idUsuario` , `cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ginecologico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ginecologico` (
  `idGinecologico` INT NOT NULL,
  `abortos` INT NULL,
  `cesareas` INT NULL,
  `fechaPrimerPeriodo` YEAR NULL,
  `fechaUltimoPeriodo` YEAR NULL,
  `gestas` VARCHAR(45) NULL,
  `metodoAnticonceptivo` VARCHAR(45) NULL,
  `partos` INT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_cedula` BIGINT(11) ZEROFILL NOT NULL,
  PRIMARY KEY (`idGinecologico`, `Usuario_idUsuario`, `Usuario_cedula`),
  INDEX `fk_Ginecologico_Usuario1_idx` (`Usuario_idUsuario` ASC, `Usuario_cedula` ASC),
  CONSTRAINT `fk_Ginecologico_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_cedula`)
    REFERENCES `mydb`.`Usuario` (`idUsuario` , `cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Antecedente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Antecedente` (
  `idAntecedente` INT NOT NULL,
  `descripcion` VARCHAR(500) NULL,
  `tipo` VARCHAR(1) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_cedula` BIGINT(11) ZEROFILL NOT NULL,
  PRIMARY KEY (`idAntecedente`, `Usuario_idUsuario`, `Usuario_cedula`),
  INDEX `fk_Antecedente_Usuario1_idx` (`Usuario_idUsuario` ASC, `Usuario_cedula` ASC),
  CONSTRAINT `fk_Antecedente_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_cedula`)
    REFERENCES `mydb`.`Usuario` (`idUsuario` , `cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MotivoUrgencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MotivoUrgencia` (
  `idmotivoUrgencia` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `inicio` DATE NULL,
  `HistoriaClinica_idhistoriaClinica` INT NOT NULL,
  `HistoriaClinica_Usuario_idUsuario` INT NOT NULL,
  `HistoriaClinica_Usuario_cedula` BIGINT(11) ZEROFILL NOT NULL,
  PRIMARY KEY (`idmotivoUrgencia`, `HistoriaClinica_idhistoriaClinica`, `HistoriaClinica_Usuario_idUsuario`, `HistoriaClinica_Usuario_cedula`),
  INDEX `fk_MotivoUrgencia_HistoriaClinica1_idx` (`HistoriaClinica_idhistoriaClinica` ASC, `HistoriaClinica_Usuario_idUsuario` ASC, `HistoriaClinica_Usuario_cedula` ASC),
  CONSTRAINT `fk_MotivoUrgencia_HistoriaClinica1`
    FOREIGN KEY (`HistoriaClinica_idhistoriaClinica` , `HistoriaClinica_Usuario_idUsuario` , `HistoriaClinica_Usuario_cedula`)
    REFERENCES `mydb`.`HistoriaClinica` (`idhistoriaClinica` , `Usuario_idUsuario` , `Usuario_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sintoma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sintoma` (
  `idSintoma` INT NOT NULL,
  `inicio` DATE NULL,
  `descripcion` VARCHAR(45) NULL,
  `nivelDolor` INT NULL,
  `MotivoUrgencia_idmotivoUrgencia` INT NOT NULL,
  `MotivoUrgencia_HistoriaClinica_idhistoriaClinica` INT NOT NULL,
  `MotivoUrgencia_HistoriaClinica_Usuario_idUsuario` INT NOT NULL,
  `MotivoUrgencia_HistoriaClinica_Usuario_cedula` BIGINT(11) ZEROFILL NOT NULL,
  PRIMARY KEY (`idSintoma`, `MotivoUrgencia_idmotivoUrgencia`, `MotivoUrgencia_HistoriaClinica_idhistoriaClinica`, `MotivoUrgencia_HistoriaClinica_Usuario_idUsuario`, `MotivoUrgencia_HistoriaClinica_Usuario_cedula`),
  INDEX `fk_Sintoma_MotivoUrgencia1_idx` (`MotivoUrgencia_idmotivoUrgencia` ASC, `MotivoUrgencia_HistoriaClinica_idhistoriaClinica` ASC, `MotivoUrgencia_HistoriaClinica_Usuario_idUsuario` ASC, `MotivoUrgencia_HistoriaClinica_Usuario_cedula` ASC),
  CONSTRAINT `fk_Sintoma_MotivoUrgencia1`
    FOREIGN KEY (`MotivoUrgencia_idmotivoUrgencia` , `MotivoUrgencia_HistoriaClinica_idhistoriaClinica` , `MotivoUrgencia_HistoriaClinica_Usuario_idUsuario` , `MotivoUrgencia_HistoriaClinica_Usuario_cedula`)
    REFERENCES `mydb`.`MotivoUrgencia` (`idmotivoUrgencia` , `HistoriaClinica_idhistoriaClinica` , `HistoriaClinica_Usuario_idUsuario` , `HistoriaClinica_Usuario_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turno` (
  `idTurno` INT NOT NULL,
  `tiempoEspera` DATE NULL,
  `Institucion_idInstitucion` INT NOT NULL,
  `Institucion_NIT` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTurno`, `Institucion_idInstitucion`, `Institucion_NIT`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
